apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ilab-ui-stack-production
spec:
  destination:
    name: instructlab-ui-prod
    namespace: instructlab
  project: default
  source:
    path: deploy/k8s/overlays/openshift/prod
    repoURL: https://github.com/instructlab/ui.git
    targetRevision: main
