apiVersion: apps/v1
kind: Deployment
metadata:
  name: doclingserve
  annotations:
    # see: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#proxy-read-timeout
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    # see: https://docs.openshift.com/container-platform/4.13/networking/routes/route-configuration.html#nw-configuring-route-timeouts_route-configuration
    haproxy.router.openshift.io/timeout: "3600s"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: doclingserve
          image: ghcr.io/ds4sd/docling-serve-cpu:main
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 5001
      restartPolicy: Always
